version: '3.1'

services:
  userapi:
    image: userapiservice
    build:
      context: .
      dockerfile: UserAPI/Dockerfile
    #environment:
      #- "ConnectionString_UserDB=Server=localhost,49173;Database=masterv3;User Id=sa;Password=Your_password123"
      #- "ConnectionString__UserDB=Server=localhost,49173;Database=masterv4;User Id=sa;Password=Your_password123"
    ports:
      - "8085:80"
  sqlserver-ab:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    extra_hosts:
      - "localhost:192.168.30.30"
    container_name: sqlserver-ab
    hostname: sqlserver-ab
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "49194:1433"